### ISSUE TITLE
Crash: Miners mining dynamic trees seems to crash the game (Crash log provided)

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#11]
Miners mining dynamic trees seems to crash the game. (https://pastebin.com/rrKjq6LN here the log) Will there be at least a blacklist for certain blocks to be ignored to prevent such things from happening? (That would also fix the problem with miners mining blocks they shouldn’t mine as they don’t respawn simply by making them not mine that block) (Making it so they can phase trough such blocks would be even better so people can’t abuse these types of blocks to make walls) I think that would fix a lot of problems.

PS: sry for opening so many different issues i try to keep them managable seperate. instead of making one big report mixed with suggestions and other bugs in one.

**Comment by Corosauce** [comment]
No worries, separate issues per actual issue is the good way to do it :+1: , just been way too busy/distracted with other stuff to put any real work into modding right now, going to catch up on a few critical ones aka crashes. I was pretty close with the blacklist feature then hit burnout and then other stuff came up.

This one specifically looks like a dynamictrees issue, my zombie may have broken it but I don't see any direct link to it. Post it to his github and mention it was broken by a mob on the server side instead of a player, might be helpful.

**Comment by SirAron111** [comment]
Thx hope you getting better soon.
