### ISSUE TITLE
Bug: Invasions not triggering at the set time anymore maybe newer forge versions changed something

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#14]
It seems like some newer forge versions or may have changed something but I set the days for the first invasion to happen to 5 and the invasion repeat time to 5 as well and have the by player function to true to make servers have less problems. I had this setting since forever in my modpack always worked great but recently it seems to not trigger the first invasion anymore. Sometimes the invasion than comes at night 10 instead and sometimes they don’t come at all until you manually change the config to a different number and than back. Is there a way to fix this so it actually triggers the first invasion again?

EDIT: maybe it has somethig to do with how minecraft always starts with day 0 and than goes to night 1 day 1 night 2 day 2 night 3 day 3 night 4 day 4 night 5...because if i set it to (0 or 4) days played untill first invasion it always pops the message at day 4 and spawns an invasion at night 5

**Comment by Corosauce** [comment]
What forge version?

I guess it makes more sense to think of the values as "nights to first invasion" instead of days etc.

Tested forge 2847 working fine:
- fresh config
- set starting day invasions per days to 5
- ran /hw_invasions setPlayerTime 110000 which sets players playtime to 4 days and a bit, makes it close enough to count as 5 days
- set time to 110000, invasion starts 

The per player counting can make what counts as enough playtime for the first invasion a bit weird so just tweak your config as needed.
