### ISSUE TITLE
Question: Small problem with Mobs breaking Blocks like Fences, stairs and Half Slabs.

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#4]
There is a small problem with Miner Mobs breaking Blocks like Fences, Stairs or Half Slabs and not turning them into repairing blocks even if the setting is enabled. I don’t know if this is to prevent them from breaking multy blocks or machines from other Mods (which is a good thing). 

But i wanted to ask if there is a way to make them turn these simple building blocks into repairing blocks as well so people don’t end up with a fenceless farms or broken stairs every invasion? IF not is it possible to have the mobs ignore these blocks making them like step over fences or seeking a path around  tunnel under it or place a scaffold like block that disappears to get over it?

(PS: Any plans for a feature to get the mobs climbing? Invasions have a hard time dealing with people on mountains when the mobs spawn at the bottom or with people building floating platforms. The hoisting feature is nice but only helps with small ledges)

**Comment by Corosauce** [comment]
Ah yeah thats not intended design, I need to improve that, I noticed it with other odd blocks like glass and did a specific fix for that one, I should be able to find a good solution for it.

Climbing might be possible to add as a cmod maaaaybe easily, worth considering yeah.

**Comment by Corosauce** [comment]
After further thought and bouncing ideas off of people, I think I will solve this with 2 black/white lists, which will also enable me to further tweak what can and cant be mined / converted to repairing block.

Block blacklist: lists things that cant be converted to repairing blocks, mainly vanilla multiblock type stuff like door, double plant, vines? sugar cane?, if modpack makers find any common mod blocks that are screwy when turned into repairing blocks they can add them to this list. Can invert list into whitelist instead.

And since all tile entities are default not mineable but I'd like some to be mineable:

Tile Entity whitelist: allow full breaking of certain tile entities, like enderio conduits which tend to line walls etc. Might experiment with seeing how sane it'd be to be able to convert things in this list to repairing block (as conduits could have upgrades in them etc, it'd be nice if it auto fixed itself). Also invertable to blacklist I guess.

If I make a basic support for convertible tile entities, maybe a 3rd whitelist, make the above one for converting to repairing block, and one for allowing full breaking. That might be making configuring things too complicated or confusing though so I need to sit on this more and think about it.

**Comment by SirAron111** [comment]
Well however it will turn out.
Your mods are all great I am using all the mob mods for my Modpack and my players love (hate) them XD.
The invasions work great being able to set custom messages for every situation is nice to give it the story flare I needed and all. Just wanted to say you are doing great work there mate.

I myself had some ideas for mods but I can’t program at all so I left it untouched, I really like the HW_Invasions Mod as it lets me pretend that the rifts from my Modpacks story are actually there. Before that I just had the Dim doors ambient ones but they don’t do anything.

https://authors.curseforge.com/forums/bounty-board/minecraft/237469-mod-idea-for-a-hostile-environment-mod#c1 that’s the idea I had before I found your mod. Currently I am using the Dimensional Doors mod to have Rifts spawn on chunk generation https://i.imgur.com/J0uyxlW.png that can be removed by the player sadly I can’t use anything else from that mod and they are a bit lackluster and once removed never appear again and they are just ambient not even spawning mobs XD. And The Invasions Mod to pretend that sometimes a Rift opens and lets monsters stream forth.

**Comment by Corosauce** [comment]
Thanks! "and my players love (hate) them XD" is pretty much exactly what I aim for xD

Ah neat, glad I could help enable a good story for the rifts.

I still kind of miss the portals/dimension feature from original hostile worlds, the whole having to venture out and put a stop to it so it stops spawning mobs. Maybe one day I'll fiddle with the idea of a central spawn point again, eg instead of randomly spawning around a player, a portal opens up near them where all invaders come out of, and might have some casual spawning after the initial invasion to promote a player going to break it. Might be more of an idea I could toss into "Hostile Worlds - Monsters" if i decide to make that mod actually be a thing with real features. I wanted that mod to have all the things invasions can do but introduced as normal world spawning, with some chunkgen that would buff certain areas. The mod hasent been fleshed out enough to merit a release of any sorts yet, also my time is limited to make anything happen currently.

Anyways back to the original issue, didn't have any time last 2 weekends, but did for this weekend. Got a great starting point for a white/black list configuration system. Still a work in progress.

Rewriting a lot of the code that decides if a block needs to be broken, and if it does, if it can be set as a repairing block.

1. First ill be checking if a block has any collision, if it doesn't the mob shouldn't have to bother mining it and just walk through it (unless a mod coded their block badly), surprised I didn't have this implemented already.

2. If the block needs to be mined and not a tile entity (chest, furnace etc), I'll check if its not allowed to be converted to a repairing block via blacklist config. Heres the proof of concept of the list i have so far:

`S:blacklistMineable_RegularBlocks=desirepaths:grass_worn_2 double_plant[variant=sunflower,half=upper] grass double_plant[variant=double_rose] stone log[0] log[1] wooden_door`

Just for testing sake it blacklists: wood door, grass, stone, grass worn stage 2, first 2 meta states of log, sunflower but only its upper half, double plant rose upper and lower halves.

To make configuring this less of a horrible pain, I've been improving how I can test this ingame.

You will be able to configure this in the config file itself, then just run "/config reload" to reload it while the game runs and see instant results (saves from having to use my ingame config gui which is a pain for long strings)

I've always wanted a better way to visualize things ingame that exist on the logical server side to show it on your client, so I implemented that, currently for blocks. You will be able to enable a client side render that shows the blocks what zombies can and cant mine with a red and green overlay on blocks, this is what it looks like currently if all the things in the blacklist have a red overlay:

![2019-03-17_22 15 24](https://user-images.githubusercontent.com/1238621/54503759-0b053480-4907-11e9-982e-2793bf499cd6.png)

Though that picture doesnt factor in the 'is tile entity' or 'has no collision' rules, so the end result would more accurately look like this with that in mind:

![2019-03-17_22 48 46](https://user-images.githubusercontent.com/1238621/54503792-312ad480-4907-11e9-9733-2bb5207a49f9.png)

I'd do the same treatment for exploded blocks converting into repairing blocks too probably.

And for tile entities, invert it, cant mine any unless you whitelist them.

Once this is fleshed out, I'd like to make it so you can configure blocks without touching a configuration file. Basically let you point and click blocks you want to blacklist from being mined, and whitelist tile entities (let modded wires/pipes/conduits get mined). If you had an already established base, you could run through it and configure things in mere minutes with this feature.

As a bonus I can use this same system on a black/whitelist for tornado damage too, once I decide to dust off that mod.

I'm about to get unavailable again for another 2 weeks or so, so unless I flesh this out nicely within the next couple days it might be a little while until this is released.

**Comment by SirAron111** [comment]
Looks great No pressure from my side take your time.
Your Mods are still some of my favorites since the Weather, Storms & Tornadoes mod  was new back in the days.

I just hope that all this extra code won’t make it lag when around 20+ Mobs run on this AI.

Also once a player has lighted up the full area around him like all 64 blocks directions mob spawns seem to slow down during invasion a bit. Is that because they need a space in darkness? If so having them ignore lighting during invasion as long as they spawn a bit away from the player would be a neat option if it’s possible.

Also for some reasons I can’t make slimes spawn with an invasion (no vanilla slimes and no Modded slimes) is there a reason for that?

Same for Ghasts or other fling mobs like the Pixies from Ice and Fire, wisps from thaumcraft or fairies from roots even when I set spawn types from ground to air. (I wanted to use them for a magical flying invasion to annoy people who simply build huge air platforms to live on as Normal invasion mobs don’t have a feature to get straight up and dig upwards)

Thx for the info on your progress and the little inside look on your coding progress. 

GZ 
SirAron
